### ISSUE TITLE
Ident issue?

### ISSUE THREAD

**Issue by Benjalien** [netllama/stuffystuff#1]
Hi,
this project seems to be exactly what I'm looking for (a script that can be called to shut down my Sonos when I leave the house - I'm lazy), but I have a Python error on line 136:
File "/usr/bin/sonos_player.py", line 136
    if not args.party:
     ^
IndentationError: expected an indented block

I know it can only be something easy to fix,but I'm a complete Python noob :(

Could you please have a look?
Thank!
Benjamin

**Comment by netllama** [comment]
Sorry about that.  It was a bug and I've pushed out a fix.

**Comment by Benjalien** [comment]
Perfect, thanks!

**Comment by Benjalien** [comment]
Hi, 

thanks for fixing so fast, may I ask you a question? (feel free to just
ignore me if you have no time :)) 

I'm looking to script the shutdown of all zones when I leave the house.
I see in the "keyboard controls" that I can pause with "P", but can I
script all at once? kind of "sonos_player --zone Cuisine -P"? 

Thanks! 

Benjamin 

Le 2019-03-07 01:55, Lonni J Friedman a écrit :

> Sorry about that. It was a bug and I've pushed out a fix. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Van Laere Benjamin
Drève du Château, 12
4020 Jupille-sur-Meuse 

Links:
------
[1]
https://github.com/netllama/stuffystuff/issues/1#issuecomment-470338728
[2]

**Comment by netllama** [comment]
Hello,
Sorry, but I don't understand what you mean by "shutdown all the zones".
Are you seeking to have your Sonos speakers stop playing?


thanks

**Comment by Benjalien** [comment]
Exactly!

**Comment by netllama** [comment]
Stopping the speakers is easy enough.  are you going to run it manually, or did you expect it to auto-detect when you leave?

**Comment by Benjalien** [comment]
I have the detection mechanism already working (for my lights and water), so I'm just looking for a script I could call to stop my speakers.

**Comment by netllama** [comment]
You just need to make a zone.stop() call, similar to how the script works.

**Comment by Benjalien** [comment]
Sorry but I'm not sure I get it. My first problem is to get the zone names (as they can be various combinations of my speakers), so I can't run zone.stop() (or at least I don't know how to do it).
BR
Benjamin
